name: ICQF
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - cvxopt
  - cython
  - ipykernel
  - ipython
  - joblib
  - jupyter_client
  - jupyter_core
  - kneed
  - matplotlib
  - numpy
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - statsmodels
  - tqdm
  - pip:
      - quadprog